

analyze_task:
  description: >
    Analyze the CV content in {parsed_cv} for {target_industry} industry.
    Focus on actual content: projects, experience, skills.
    Identify which projects should be prioritized and what needs improvement.
  expected_output: >
    **ANALYSIS:**
    - **Strengths:** [Quote specific achievements from CV]
    - **Priority Project:** [Which project should be listed first and why]  
    - **Improvements Needed:** [Specific sections that need enhancement]
    - **Missing Keywords:** [For {target_industry} and ATS optimization]
  agent: cv_analyst

enhance_task:
  description: >
    Based on the analysis, provide specific enhancement recommendations.
    Quote original content and provide improved versions.
    Focus on quantifying achievements and industry alignment for {target_industry}.
  expected_output: >
    **ENHANCEMENTS:**
    - **Project Reordering:** [Recommended priority order with reasons]
    - **Experience Improvements:** [Original → Enhanced versions]
    - **Skills Updates:** [What to add/emphasize for {target_industry}]
    - **ATS Keywords:** [Specific terms to include]
    - **Final Recommendations:** [Top 3 actionable improvements]
  agent: cv_writer
